# Generated by Django 4.2.4 on 2023-11-17 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ministry', '0002_ministry_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('media', 'media'), ('choir', 'choir'), ('usering', 'ushering'), ('staff', 'staff'), ('follow-up', 'follow-up')], max_length=155)),
                ('description', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='ministry.ministry')),
            ],
            options={
                'verbose_name_plural': 'departments',
            },
        ),
    ]
