# Generated by Django 4.2.4 on 2023-11-17 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ministry', '0003_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministry',
            name='created_by',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ministries', to=settings.AUTH_USER_MODEL),
        ),
    ]
