# Generated by Django 4.2.4 on 2023-11-19 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ministry', '0008_remove_member_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('image', models.ImageField(default='', upload_to='static/images')),
                ('phone_number', models.IntegerField()),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ministry.cell')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ministry.department')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ministry.ministry')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
