# Generated by Django 4.2.4 on 2023-11-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0010_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/'),
        ),
    ]
