# Generated by Django 4.2.4 on 2023-11-09 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('brother', 'brother'), ('sister', 'sister'), ('pastor', 'pastor'), ('Deacon', 'Deacon'), ('Deaconess', 'Deaconess')], max_length=50)),
                ('profile_picture', models.ImageField(default='', upload_to='')),
                ('phone_number', models.PositiveIntegerField(null=True)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('about', models.CharField(blank=True, max_length=160, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
