# Generated by Django 4.2.4 on 2023-11-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='user.username', max_length=200),
        ),
    ]
